# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
    env:
      NEXT_PUBLIC_TMDB_IMAGE_URL: ${{ secrets.NEXT_PUBLIC_TMDB_IMAGE_URL }},
      TMDB_API_CALL: ${{ secrets.TMDB_API_CALL }},
      TMDB_DISCOVER_MOVIES: ${{ secrets.TMDB_DISCOVER_MOVIES }},
      TMDB_LANGUAGE: ${{ secrets.TMDB_LANGUAGE }},
      TMDB_URL: ${{ secrets.TMDB_URL }},
      TMDB_WITH_GENRES: ${{ secrets.TMDB_WITH_GENRES }}
    - run: npm run lint
    - run: npm test
